name: OS matrix
on: [push]
jobs:
  build:
    name: OS matrix
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Print runner OS
        run: echo "Running on ${{runner.os}}."
        shell: bash